// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WhitelistSpots$Type } from "./WhitelistSpots";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WhitelistSpots"]: WhitelistSpots$Type;
    ["contracts/rewards/WhitelistSpotsReward.sol:WhitelistSpots"]: WhitelistSpots$Type;
  }

  interface ContractTypesMap {
    ["WhitelistSpots"]: GetContractReturnType<WhitelistSpots$Type["abi"]>;
    ["contracts/rewards/WhitelistSpotsReward.sol:WhitelistSpots"]: GetContractReturnType<WhitelistSpots$Type["abi"]>;
  }
}
