// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HoldXTokens$Type } from "./HoldXTokens";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HoldXTokens"]: HoldXTokens$Type;
    ["contracts/activities/HoldXTokensActivity.sol:HoldXTokens"]: HoldXTokens$Type;
  }

  interface ContractTypesMap {
    ["HoldXTokens"]: GetContractReturnType<HoldXTokens$Type["abi"]>;
    ["contracts/activities/HoldXTokensActivity.sol:HoldXTokens"]: GetContractReturnType<HoldXTokens$Type["abi"]>;
  }
}
