// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MerkleProof$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MerkleProof",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220a6017a4435975e2465017eba35e5d6c2d6ea5e7bc5fec5ec2ff85e5ee420077d64736f6c63430008140033",
  "deployedBytecode": "0x600080fdfea2646970667358221220a6017a4435975e2465017eba35e5d6c2d6ea5e7bc5fec5ec2ff85e5ee420077d64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MerkleProof",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MerkleProof",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MerkleProof$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MerkleProof$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MerkleProof",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
}
