// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TokenRaffleReward$Type } from "./TokenRaffleReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenRaffleReward"]: TokenRaffleReward$Type;
    ["contracts/rewards/TokenRaffleReward.sol:TokenRaffleReward"]: TokenRaffleReward$Type;
  }

  interface ContractTypesMap {
    ["TokenRaffleReward"]: GetContractReturnType<TokenRaffleReward$Type["abi"]>;
    ["contracts/rewards/TokenRaffleReward.sol:TokenRaffleReward"]: GetContractReturnType<TokenRaffleReward$Type["abi"]>;
  }
}
