// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Tim3capFactory$Type } from "./Tim3capFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Tim3capFactory"]: Tim3capFactory$Type;
    ["contracts/Tim3capFactory.sol:Tim3capFactory"]: Tim3capFactory$Type;
  }

  interface ContractTypesMap {
    ["Tim3capFactory"]: GetContractReturnType<Tim3capFactory$Type["abi"]>;
    ["contracts/Tim3capFactory.sol:Tim3capFactory"]: GetContractReturnType<Tim3capFactory$Type["abi"]>;
  }
}
