// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WhitelistRaffleReward$Type } from "./WhitelistRaffleReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WhitelistRaffleReward"]: WhitelistRaffleReward$Type;
    ["contracts/rewards/WhitelistRaffleReward.sol:WhitelistRaffleReward"]: WhitelistRaffleReward$Type;
  }

  interface ContractTypesMap {
    ["WhitelistRaffleReward"]: GetContractReturnType<WhitelistRaffleReward$Type["abi"]>;
    ["contracts/rewards/WhitelistRaffleReward.sol:WhitelistRaffleReward"]: GetContractReturnType<WhitelistRaffleReward$Type["abi"]>;
  }
}
