// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestNFT$Type } from "./TestNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestNFT"]: TestNFT$Type;
    ["contracts/test/TestNFT.sol:TestNFT"]: TestNFT$Type;
  }

  interface ContractTypesMap {
    ["TestNFT"]: GetContractReturnType<TestNFT$Type["abi"]>;
    ["contracts/test/TestNFT.sol:TestNFT"]: GetContractReturnType<TestNFT$Type["abi"]>;
  }
}
