// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IActivity$Type } from "./IActivity";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IActivity"]: IActivity$Type;
    ["contracts/interfaces/IActivity.sol:IActivity"]: IActivity$Type;
  }

  interface ContractTypesMap {
    ["IActivity"]: GetContractReturnType<IActivity$Type["abi"]>;
    ["contracts/interfaces/IActivity.sol:IActivity"]: GetContractReturnType<IActivity$Type["abi"]>;
  }
}
