// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BuyXApecoinWorthOfTokens$Type } from "./BuyXApecoinWorthOfTokens";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BuyXApecoinWorthOfTokens"]: BuyXApecoinWorthOfTokens$Type;
    ["contracts/activities/BuyXApecoinWorthOfTokensActivity.sol:BuyXApecoinWorthOfTokens"]: BuyXApecoinWorthOfTokens$Type;
  }

  interface ContractTypesMap {
    ["BuyXApecoinWorthOfTokens"]: GetContractReturnType<BuyXApecoinWorthOfTokens$Type["abi"]>;
    ["contracts/activities/BuyXApecoinWorthOfTokensActivity.sol:BuyXApecoinWorthOfTokens"]: GetContractReturnType<BuyXApecoinWorthOfTokens$Type["abi"]>;
  }
}
