// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeERC20$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeERC20",
  "sourceName": "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220bec32e602ef477a52cf552047199448b0ca5afa060593bdbc2e06dc19fbbc60464736f6c63430008140033",
  "deployedBytecode": "0x600080fdfea2646970667358221220bec32e602ef477a52cf552047199448b0ca5afa060593bdbc2e06dc19fbbc60464736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeERC20",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeERC20",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeERC20$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeERC20$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeERC20",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;
}
