// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface console$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "console",
  "sourceName": "hardhat/console.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220ddbd645725cd72eb65c254af78aa8a96d5cd897fb80011bb110bd6135c03e5d864736f6c63430008140033",
  "deployedBytecode": "0x600080fdfea2646970667358221220ddbd645725cd72eb65c254af78aa8a96d5cd897fb80011bb110bd6135c03e5d864736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "console",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
  export function deployContract(
    contractName: "hardhat/console.sol:console",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "console",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<console$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "hardhat/console.sol:console",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<console$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "console",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
  export function getContractAt(
    contractName: "hardhat/console.sol:console",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
}
