// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Strings$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Strings",
  "sourceName": "@openzeppelin/contracts/utils/Strings.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212208ac13cdd8d0521d52154beaad57d8f3cc20a79075a6c37c2dade85202f447f3264736f6c63430008140033",
  "deployedBytecode": "0x600080fdfea26469706673582212208ac13cdd8d0521d52154beaad57d8f3cc20a79075a6c37c2dade85202f447f3264736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Strings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Strings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Strings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Strings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Strings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
}
