// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TokenAirdropReward$Type } from "./TokenAirdropReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenAirdropReward"]: TokenAirdropReward$Type;
    ["contracts/rewards/TokenAirdropReward.sol:TokenAirdropReward"]: TokenAirdropReward$Type;
  }

  interface ContractTypesMap {
    ["TokenAirdropReward"]: GetContractReturnType<TokenAirdropReward$Type["abi"]>;
    ["contracts/rewards/TokenAirdropReward.sol:TokenAirdropReward"]: GetContractReturnType<TokenAirdropReward$Type["abi"]>;
  }
}
