// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HoldXNfts$Type } from "./HoldXNfts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HoldXNfts"]: HoldXNfts$Type;
    ["contracts/activities/HoldXNftsActivity.sol:HoldXNfts"]: HoldXNfts$Type;
  }

  interface ContractTypesMap {
    ["HoldXNfts"]: GetContractReturnType<HoldXNfts$Type["abi"]>;
    ["contracts/activities/HoldXNftsActivity.sol:HoldXNfts"]: GetContractReturnType<HoldXNfts$Type["abi"]>;
  }
}
