// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NFTRaffleReward$Type } from "./NFTRaffleReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NFTRaffleReward"]: NFTRaffleReward$Type;
    ["contracts/rewards/NFTRaffleReward.sol:NFTRaffleReward"]: NFTRaffleReward$Type;
  }

  interface ContractTypesMap {
    ["NFTRaffleReward"]: GetContractReturnType<NFTRaffleReward$Type["abi"]>;
    ["contracts/rewards/NFTRaffleReward.sol:NFTRaffleReward"]: GetContractReturnType<NFTRaffleReward$Type["abi"]>;
  }
}
