// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IReward$Type } from "./IReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IReward"]: IReward$Type;
    ["contracts/interfaces/IReward.sol:IReward"]: IReward$Type;
  }

  interface ContractTypesMap {
    ["IReward"]: GetContractReturnType<IReward$Type["abi"]>;
    ["contracts/interfaces/IReward.sol:IReward"]: GetContractReturnType<IReward$Type["abi"]>;
  }
}
