// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BuyXApecoinWorthOfNFTs$Type } from "./BuyXApecoinWorthOfNFTs";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BuyXApecoinWorthOfNFTs"]: BuyXApecoinWorthOfNFTs$Type;
    ["contracts/activities/BuyXApecoinWorthOfNFTsActivity.sol:BuyXApecoinWorthOfNFTs"]: BuyXApecoinWorthOfNFTs$Type;
  }

  interface ContractTypesMap {
    ["BuyXApecoinWorthOfNFTs"]: GetContractReturnType<BuyXApecoinWorthOfNFTs$Type["abi"]>;
    ["contracts/activities/BuyXApecoinWorthOfNFTsActivity.sol:BuyXApecoinWorthOfNFTs"]: GetContractReturnType<BuyXApecoinWorthOfNFTs$Type["abi"]>;
  }
}
