// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Tim3capRegistry$Type } from "./Tim3capRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Tim3capRegistry"]: Tim3capRegistry$Type;
    ["contracts/Tim3capRegistery.sol:Tim3capRegistry"]: Tim3capRegistry$Type;
  }

  interface ContractTypesMap {
    ["Tim3capRegistry"]: GetContractReturnType<Tim3capRegistry$Type["abi"]>;
    ["contracts/Tim3capRegistery.sol:Tim3capRegistry"]: GetContractReturnType<Tim3capRegistry$Type["abi"]>;
  }
}
