// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MerkleWhitelistReward$Type } from "./MerkleWhitelistReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MerkleWhitelistReward"]: MerkleWhitelistReward$Type;
    ["contracts/rewards/WLSpotReward.sol:MerkleWhitelistReward"]: MerkleWhitelistReward$Type;
  }

  interface ContractTypesMap {
    ["MerkleWhitelistReward"]: GetContractReturnType<MerkleWhitelistReward$Type["abi"]>;
    ["contracts/rewards/WLSpotReward.sol:MerkleWhitelistReward"]: GetContractReturnType<MerkleWhitelistReward$Type["abi"]>;
  }
}
