// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Tim3cap$Type } from "./Tim3cap";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Tim3cap"]: Tim3cap$Type;
    ["contracts/Tim3cap.sol:Tim3cap"]: Tim3cap$Type;
  }

  interface ContractTypesMap {
    ["Tim3cap"]: GetContractReturnType<Tim3cap$Type["abi"]>;
    ["contracts/Tim3cap.sol:Tim3cap"]: GetContractReturnType<Tim3cap$Type["abi"]>;
  }
}
