// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BuyXTokens$Type } from "./BuyXTokens";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BuyXTokens"]: BuyXTokens$Type;
    ["contracts/activities/BuyXTokensActivity.sol:BuyXTokens"]: BuyXTokens$Type;
  }

  interface ContractTypesMap {
    ["BuyXTokens"]: GetContractReturnType<BuyXTokens$Type["abi"]>;
    ["contracts/activities/BuyXTokensActivity.sol:BuyXTokens"]: GetContractReturnType<BuyXTokens$Type["abi"]>;
  }
}
