// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Clones$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Clones",
  "sourceName": "@openzeppelin/contracts/proxy/Clones.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220d99e178a99638baa2be14e5914e2754b29ab25befdc424d6ce0ace8ba51fed9c64736f6c63430008140033",
  "deployedBytecode": "0x600080fdfea2646970667358221220d99e178a99638baa2be14e5914e2754b29ab25befdc424d6ce0ace8ba51fed9c64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Clones",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Clones",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Clones$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Clones$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Clones",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
}
