// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NFTAirdropReward$Type } from "./NFTAirdropReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NFTAirdropReward"]: NFTAirdropReward$Type;
    ["contracts/rewards/NFTAirdropReward.sol:NFTAirdropReward"]: NFTAirdropReward$Type;
  }

  interface ContractTypesMap {
    ["NFTAirdropReward"]: GetContractReturnType<NFTAirdropReward$Type["abi"]>;
    ["contracts/rewards/NFTAirdropReward.sol:NFTAirdropReward"]: GetContractReturnType<NFTAirdropReward$Type["abi"]>;
  }
}
