// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NFTMintReward$Type } from "./NFTMintReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NFTMintReward"]: NFTMintReward$Type;
    ["contracts/rewards/NFTMintReward.sol:NFTMintReward"]: NFTMintReward$Type;
  }

  interface ContractTypesMap {
    ["NFTMintReward"]: GetContractReturnType<NFTMintReward$Type["abi"]>;
    ["contracts/rewards/NFTMintReward.sol:NFTMintReward"]: GetContractReturnType<NFTMintReward$Type["abi"]>;
  }
}
