// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Tim3capInitializer$Type } from "./Tim3capInitializer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Tim3capInitializer"]: Tim3capInitializer$Type;
    ["contracts/Tim3capInitializer.sol:Tim3capInitializer"]: Tim3capInitializer$Type;
  }

  interface ContractTypesMap {
    ["Tim3capInitializer"]: GetContractReturnType<Tim3capInitializer$Type["abi"]>;
    ["contracts/Tim3capInitializer.sol:Tim3capInitializer"]: GetContractReturnType<Tim3capInitializer$Type["abi"]>;
  }
}
