// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BaseReward$Type } from "./BaseReward";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseReward"]: BaseReward$Type;
    ["contracts/BaseReward.sol:BaseReward"]: BaseReward$Type;
  }

  interface ContractTypesMap {
    ["BaseReward"]: GetContractReturnType<BaseReward$Type["abi"]>;
    ["contracts/BaseReward.sol:BaseReward"]: GetContractReturnType<BaseReward$Type["abi"]>;
  }
}
